onboarding = false

[theme]
name = "catppuccin"

[keys]
prefix = "ctrl+a"

# Session/workspace navigation
detach = ["alt+q", "prefix+d", "prefix+q"]
goto = ["alt+s", "prefix+w", "prefix+g"]
workspace_picker = "prefix+s"
settings = "prefix+shift+s"
previous_workspace = ["cmd+alt+up", "ctrl+alt+up"]
next_workspace = ["cmd+alt+down", "ctrl+alt+down"]

# Tabs
new_tab = ["alt+t", "prefix+c"]
rename_tab = ["alt+shift+t", "prefix+comma", "prefix+shift+t"]
previous_tab = ["alt+shift+left", "prefix+p"]
next_tab = ["alt+shift+right", "prefix+n"]
move_tab_previous = "alt+i"
move_tab_next = "alt+o"
switch_tab = ["alt+1..9", "prefix+1..9"]
close_tab = ["prefix+ampersand", "prefix+shift+x"]

# Agents
previous_agent = ["alt+shift+up", "prefix+["]
next_agent = ["alt+shift+down", "prefix+]"]
focus_agent = "prefix+alt+1..9"

# Panes
split_vertical = ["cmd+d", "alt+n", "alt+shift+r", "prefix+shift+backslash"]
split_horizontal = ["cmd+shift+d", "alt+shift+d", "prefix+minus"]
cycle_pane_next = "prefix+o"
last_pane = "prefix+semicolon"
close_pane = ["alt+shift+w", "prefix+x"]
zoom = ["alt+z", "prefix+m", "prefix+z"]
edit_scrollback = ["alt+e", "prefix+e"]
resize_pane_left = "prefix+left"
resize_pane_down = "prefix+down"
resize_pane_up = "prefix+up"
resize_pane_right = "prefix+right"
resize_mode = "prefix+shift+r"
reload_config = "prefix+r"


# Seamless pane navigation
[[keys.command]]
key = "alt+left"
type = "plugin_action"
command = "herdr-splits.nav-left"
description = "navigate left across Neovim and Herdr"

[[keys.command]]
key = "alt+down"
type = "plugin_action"
command = "herdr-splits.nav-down"
description = "navigate down across Neovim and Herdr"

[[keys.command]]
key = "alt+up"
type = "plugin_action"
command = "herdr-splits.nav-up"
description = "navigate up across Neovim and Herdr"

[[keys.command]]
key = "alt+right"
type = "plugin_action"
command = "herdr-splits.nav-right"
description = "navigate right across Neovim and Herdr"

[[keys.command]]
key = "alt+shift+s"
type = "popup"
command = "\"$HOME/bin/herdr-sessionizer\""
description = "project workspace picker"
width = "80%"
height = "60%"

[ui]
sidebar_collapsed_mode ="hidden"
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"
prompt_new_tab_name = false
hide_tab_bar_when_single_tab = true
pane_outer_borders = false
pane_gaps = false
status_indicators = "symbols"
tab_bar_position = "bottom"
